name: go

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to go.mod
        type: string
        required: true
      cache-dependency-path:
        description: Path to go.sum
        type: string
        required: true
      golangci-lint-version:
        description: golangci-lint version
        type: string
        required: false

jobs:
  lint:
    if: inputs.golangci-lint-version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: ${{ inputs.golangci-lint-version }}
          args: --timeout=3m

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: go mod tidy
      - run: make fmt
      - run: make generate manifests
      - uses: int128/update-generated-files-action@6ac8557861efc7d8c34f4e3f182f9c39b26e6e76 # v2.53.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: make test
