name: go

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to go.mod
        type: string
        required: true
      cache-dependency-path:
        description: Path to go.sum
        type: string
        required: true
      golangci-lint-version:
        description: golangci-lint version
        type: string
        required: false

jobs:
  lint:
    if: inputs.golangci-lint-version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: ${{ inputs.golangci-lint-version }}
          args: --timeout=3m

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: go mod tidy
      - run: make fmt
      - run: make generate manifests
      - uses: int128/update-generated-files-action@d01a193ae8a14d7d7699981665a0922bde444389 # v2.52.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: make test
