name: manifest

on:
  workflow_call:
    inputs:
      kustomization:
        description: glob patterns to kustomization.yaml
        type: string
        default: |
          config/default/kustomization.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@4aede2c006f8839192901e46ac080fc5a084bd63 # v1.151.0
        id: kustomize-head
        with:
          base-directory: head
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true

      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@4aede2c006f8839192901e46ac080fc5a084bd63 # v1.151.0
        id: kustomize-base
        with:
          base-directory: base
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true
          ignore-kustomize-error: true

      - uses: int128/diff-action@3a59d251072267b26298f1399ec8ced248ff120b # v1.44.0
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
