name: manifest

on:
  workflow_call:
    inputs:
      kustomization:
        description: glob patterns to kustomization.yaml
        type: string
        default: |
          config/default/kustomization.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@94de1dfdbd8db6b9aca4f34cb0971fe948b7de6f # v1.147.0
        id: kustomize-head
        with:
          base-directory: head
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@94de1dfdbd8db6b9aca4f34cb0971fe948b7de6f # v1.147.0
        id: kustomize-base
        with:
          base-directory: base
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true
          ignore-kustomize-error: true

      - uses: int128/diff-action@572745834305133cec12a2db4ee2015625aa4ec3 # v1.42.0
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
