name: manifest

on:
  workflow_call:
    inputs:
      kustomization:
        description: glob patterns to kustomization.yaml
        type: string
        default: |
          config/default/kustomization.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@0293525c1c198e5f09352da2ab913b876f9ca5ea # v1.158.0
        id: kustomize-head
        with:
          base-directory: head
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@0293525c1c198e5f09352da2ab913b876f9ca5ea # v1.158.0
        id: kustomize-base
        with:
          base-directory: base
          kustomization: ${{ inputs.kustomization }}
          write-individual-files: true
          ignore-kustomize-error: true

      - uses: int128/diff-action@11d13836f3903363aa010d55be585ed77c9d6ea8 # v1.54.0
        id: diff
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
          comment: false
      - uses: int128/comment-action@e342425defa04431c2adb276469c04a28b539269 # v1.38.0
        with:
          update-if-exists: replace
          post: |
            ## kustomize diff
            ${{ steps.diff.outputs.comment-body }}
