name: test

on:
  pull_request:
  push:
    branches:
      - v1

jobs:
  go:
    uses: ./.github/workflows/go.yaml
    with:
      go-version: 1.21.0
      golangci-lint-version: v1.54.0

  manifest:
    uses: ./.github/workflows/manifest.yaml
