name: test

on:
  pull_request:
  push:
    branches:
      - v1

jobs:
  go:
    uses: ./.github/workflows/go.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      go-version-file: go.mod
      golangci-lint-version: v1.60.3

  manifest:
    uses: ./.github/workflows/manifest.yaml
    permissions:
      contents: read
      pull-requests: write

  release:
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: write
