name: test

on:
  pull_request:
  push:
    branches:
      - v1

jobs:
  go:
    uses: ./.github/workflows/go.yaml
    with:
      go-version-file: go.mod
      golangci-lint-version: v1.57.2

  manifest:
    uses: ./.github/workflows/manifest.yaml
